site_name: Kubeform.io Documentation
site_description: Documentation and resources for using the Kubeform modules.
site_author: Kubeform.io Team
copyright: Copyright &copy; 2023 to Present, Kubeform.io
use_directory_urls: false
docs_dir: ../
site_dir: !ENV SITE_DIRECTORY
site_url: https://kubeform.io
repo_name: kubeform-io.gitlab.io
repo_url: https://github.com/kubeform-io/kubeform-io.gitlab.io
edit_uri: edit/main/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kubeform-io
theme:
  name: material
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
plugins:
  - search
  - tags
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
      line_spans: __span
      linenums: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      social_url_shortener: true
      provider: 'github'
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: kubeform-io
      repo: kubeform-io.gitlab.io
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde